export enum ErrorCode {
    UNKNOWN_ERROR,
    UNKNOWN_PRISMA_ERROR,
    VALIDATION_ERROR,
    DATABASE_ERROR,
    UNIQUE_CONSTRAINT_ERROR,
    FOREIGN_KEY_CONSTRAINT_ERROR,
    RECORD_NOT_FOUND_ERROR,
    AUTHORIZATION_ERROR
}